import type { ConvAIReplicaPreset } from './types';

export const biotuneBrandProfile: ConvAIReplicaPreset = {
  id: 'biotune',
  label: 'BioTune',
  description:
    'BioTune baseline branding preset. Update logo/image URLs here to keep them source-controlled.',
  settings: {
    variant: 'full',
    placement: 'bottom-right',
    conversationMode: 'voice-and-text',
    dismissible: true,
    actionText: 'Talk to interrupt',
    expandText: 'Welcome Need Help?',
    orbDebug: false,
    avatarImageUrl: '',
    secondaryLogoUrl: '',
    secondaryLogoSize: 42,
    secondaryLogoOffsetX: 18,
    secondaryLogoOffsetY: 51,
    secondaryLogoRounded: true,
    secondaryLogoShadow: true,
    providerText: 'Provided by WingSpanAi.com.au',
    providerUrl: 'https://wingspanai.com.au',
    providerIconUrl: '/wingspan-favicon.ico',
    providerIconSize: 12,
    providerOffsetY: 6,
    poweredByTextOverride: 'Powered by GRABiT-Labs',
    useOrbColors: true,
    avatarOrbColor1: '#16A34A',
    avatarOrbColor2: '#14B8A6',
    useWidgetThemeColors: true,
    widgetBaseColor: '#F0FDF4',
    widgetBasePrimaryColor: '#14532D',
    widgetBaseBorderColor: '#86EFAC',
    widgetBaseSubtleColor: '#15803D',
    widgetAccentColor: '#15803D',
    widgetAccentPrimaryColor: '#F0FDF4',
    inputBoxShrinkPx: 6,
    inputTextLiftPx: 6,
    dynamicVariablesInput: '{\n  "source": "convai-replica",\n  "build": "biotune"\n}',
  },
};
